/**
 * Stable type definitions for BetterRTX shader manifests.
 *
 * These interfaces define the shape of manifest data used by the compilation
 * pipeline. The actual manifest data is loaded at runtime from an embedded
 * JSON file (generated by scripts/setup.ts).
 */

import type { ShaderStage } from "../material/enums.ts";

/** Metadata for a single shader to be compiled. */
export interface ShaderEntry {
  /** Display name (e.g., "RTXStub.Vertex"). */
  readonly name: string;
  /** Filename in the embedded shaders directory. */
  readonly fileName: string;
  /** Vertex, Fragment, or Compute. */
  readonly stage: ShaderStage;
  /** HLSL entry point function name. */
  readonly entryPoint: string;
  /** DXC target profile (e.g., "vs_6_5", "ps_6_5", "cs_6_5"). */
  readonly targetProfile: string;
  /** Optional preprocessor defines. */
  readonly defines?: Readonly<Record<string, string>>;
  /** Additional DXC compiler arguments (e.g., ["-enable-16bit-types", "-Qstrip_reflect"]). */
  readonly compilerOptions?: readonly string[];
}

/** A material manifest defines one .material.bin output. */
export interface MaterialManifest {
  /** Name used in the Material header. */
  readonly materialName: string;
  /** Primary pass name (used when all shaders belong to one pass). */
  readonly passName: string;
  /** Shaders to compile for this material. */
  readonly shaders: readonly ShaderEntry[];
  /** Compiler-wide options applied to all shaders in this material. */
  readonly compilerOptions?: readonly string[];
}
